/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VButton {
    }
    interface VModal {
        "isOpen": Boolean;
        "maxWidth": string;
        "modalId": string;
        "modalTitle": string;
    }
}
declare global {
    interface HTMLVButtonElement extends Components.VButton, HTMLStencilElement {
    }
    var HTMLVButtonElement: {
        prototype: HTMLVButtonElement;
        new (): HTMLVButtonElement;
    };
    interface HTMLVModalElement extends Components.VModal, HTMLStencilElement {
    }
    var HTMLVModalElement: {
        prototype: HTMLVModalElement;
        new (): HTMLVModalElement;
    };
    interface HTMLElementTagNameMap {
        "v-button": HTMLVButtonElement;
        "v-modal": HTMLVModalElement;
    }
}
declare namespace LocalJSX {
    interface VButton {
    }
    interface VModal {
        "isOpen"?: Boolean;
        "maxWidth"?: string;
        "modalId"?: string;
        "modalTitle"?: string;
        "onClosed"?: (event: CustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "v-button": VButton;
        "v-modal": VModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "v-button": LocalJSX.VButton & JSXBase.HTMLAttributes<HTMLVButtonElement>;
            "v-modal": LocalJSX.VModal & JSXBase.HTMLAttributes<HTMLVModalElement>;
        }
    }
}
