/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VButton {
    }
    interface VCancelIcon {
    }
    interface VModal {
        "isOpen": boolean;
        "maxWidth": string;
        "modalId": string;
        "modalTitle": string;
    }
    interface VSvgIcon {
        "size": number;
    }
}
declare global {
    interface HTMLVButtonElement extends Components.VButton, HTMLStencilElement {
    }
    var HTMLVButtonElement: {
        prototype: HTMLVButtonElement;
        new (): HTMLVButtonElement;
    };
    interface HTMLVCancelIconElement extends Components.VCancelIcon, HTMLStencilElement {
    }
    var HTMLVCancelIconElement: {
        prototype: HTMLVCancelIconElement;
        new (): HTMLVCancelIconElement;
    };
    interface HTMLVModalElement extends Components.VModal, HTMLStencilElement {
    }
    var HTMLVModalElement: {
        prototype: HTMLVModalElement;
        new (): HTMLVModalElement;
    };
    interface HTMLVSvgIconElement extends Components.VSvgIcon, HTMLStencilElement {
    }
    var HTMLVSvgIconElement: {
        prototype: HTMLVSvgIconElement;
        new (): HTMLVSvgIconElement;
    };
    interface HTMLElementTagNameMap {
        "v-button": HTMLVButtonElement;
        "v-cancel-icon": HTMLVCancelIconElement;
        "v-modal": HTMLVModalElement;
        "v-svg-icon": HTMLVSvgIconElement;
    }
}
declare namespace LocalJSX {
    interface VButton {
    }
    interface VCancelIcon {
    }
    interface VModal {
        "isOpen"?: boolean;
        "maxWidth"?: string;
        "modalId"?: string;
        "modalTitle"?: string;
        "onClosed"?: (event: CustomEvent<string>) => void;
    }
    interface VSvgIcon {
        "size"?: number;
    }
    interface IntrinsicElements {
        "v-button": VButton;
        "v-cancel-icon": VCancelIcon;
        "v-modal": VModal;
        "v-svg-icon": VSvgIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "v-button": LocalJSX.VButton & JSXBase.HTMLAttributes<HTMLVButtonElement>;
            "v-cancel-icon": LocalJSX.VCancelIcon & JSXBase.HTMLAttributes<HTMLVCancelIconElement>;
            "v-modal": LocalJSX.VModal & JSXBase.HTMLAttributes<HTMLVModalElement>;
            "v-svg-icon": LocalJSX.VSvgIcon & JSXBase.HTMLAttributes<HTMLVSvgIconElement>;
        }
    }
}
